name = "Spirit SMP"
author = "Spirit Studios"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31adc7ef4242ac64b06a9ce9f74b93a7d81fd461efc8f237f65ddb5b9c63cb50"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
