name = "Spirit SMP"
author = "Spirit Studios"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "364bfdf287862fbca6f5f031e52fd4700b196286f7ccfc257893a6ff2b935854"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
