name = "Spirit SMP"
author = "Spirit Studios"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb1b090999f16375547630dea6e2ac9d5441c5f9f0f92b29257bcf204c8be344"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
