name = "Spirit SMP"
author = "Spirit Studios"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b93990ff70f5b9870231f6393498aea1b5561de873fce7359ecd447c276c116"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
