name = "Spirit SMP"
author = "Spirit Studios"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd410a352d3cc6fe598b8c17e7f6e9224b17a9c2889dd8eaa59ab0d246ed3268"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
