name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f92ac2008178c2c7341f6a8c2f2b32a633cf70de2b6c119cdf551698d024407"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
