name = "Spirit SMP"
author = "Spirit Studios"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "720f35188d1d087352bf43da6c31597209348520ed0f44b535960640e597e491"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
