name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "442309224a00981e58a20dd28249386708a55e2acd79e76c49373e442c2ceb37"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
