name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f646d7a98a91bbafe7d958af1dd8604e3642edb67c1f139dab62060e636a718d"

[versions]
fabric = "0.16.2"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21.1"]
