name = "Spirit SMP"
author = "Spirit Studios"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fd260766183dfbb69fd76da4db54a3cbd7835837713c410e54b634e165c5c8c"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
