name = "Spirit SMP"
author = "Spirit Studios"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e565134fab47359c36887f1de5b133ed56706f124f281708028c986c965ea239"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
