ame = "Spirit SMP"
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a7d64611462416606858d176c2a5ddc31754b7e0c4115c5c03ae4232e81443b"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
