name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd7aa83a13c63f26559ea4576b0b32462e181edede3216b626dd6f138fb52862"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
