name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b11df031dae2e032fd7cb3f76702b3fbeefbb16c3bdae93363b09d5a62c54199"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
