name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d016eade2ca1c439dedd48de2f243949c49a42eb1dc4941ec7b6a79402e0e5a1"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
