name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9af4d1ebde4ea3d9d906970d7ef971568655a58d39a28275ef677cb2e36d0acc"

[versions]
fabric = "0.16.2"
minecraft = "1.21"

[options]
datapack-folder = "datapacks"
