name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cc28fe5477e3027faaaeb9cd9201229444c07d71e9ae803e636dcec6619a598"

[versions]
fabric = "0.16.2"
minecraft = "1.21"

[options]
datapack-folder = "datapacks"
