name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "843bd40a174050694de779e11428be7b6bd74c41af90416aa51589fd938e426e"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
