name = "Spirit SMP"
author = "Spirit Studios"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3190cd4766057c8c3ed766a1ede9e6a6852d6b28b2526a3512eeb855112a7735"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
