name = "Spirit SMP"
author = "Spirit Studios"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bd13339a9420d99349d8cb43280c9a3dbf5fec0a26e8728adbc1e66fe934840"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
