name = "Spirit SMP"
author = "Spirit Studios"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96072186fdfa17799f9bccb3194de30085390de98c7efd73eb00cbaedf95de1e"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
