name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebe89ac9d59df29a75f2bf1a346668aa97a142df5894f8c35a1e3cea86e3d3aa"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
