name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f294592fb2ec138f45340e7f43014bfc662431dacd3796fe5c08f55532433a4e"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
