name = "Spirit SMP"
author = "Spirit Studios"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c754e63376b1a7c13690df982b4dfaad1123455b5e9485c80524741760453560"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
