name = ""
author = "Spirit Studios"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "062097f1f087ab9407a1c5b938c19fb5cc2b355426cd28bf57e80b65aeee0c9d"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
